-- Create a dev admin user and API key for testing
-- Run this inside the postgres container or via psql

-- Insert admin user (if not exists)
INSERT INTO users (email, name, oidc_sub)
VALUES (
    'admin@dev.local',
    'Dev Admin',
    'dev-admin-oidc-sub'
)
ON CONFLICT (email) DO NOTHING
RETURNING id;

-- Get the user ID (since it's a UUID generated by the database)
-- Store it in a variable for the next command
DO $$
DECLARE
    v_user_id uuid;
BEGIN
    SELECT id INTO v_user_id FROM users WHERE email = 'admin@dev.local';
    RAISE NOTICE 'User ID: %', v_user_id;
    
    -- Create API key for the admin user
    -- The actual API key string is: dev_XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx
    -- The key_hash is bcrypt($2a$10) of the key
    -- key_prefix is the first 10 chars: dev_XxXxXx
    INSERT INTO api_keys (user_id, name, key_hash, key_prefix, scopes, created_at)
    VALUES (
        v_user_id,
        'Development API Key',
        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', -- bcrypt hash of "secret"
        'dev_secret',
        '["admin"]'::jsonb,
        NOW()
    )
    ON CONFLICT (key_hash) DO UPDATE
    SET scopes = EXCLUDED.scopes;
END $$;

-- Verify the user was created
SELECT id, email, name FROM users WHERE email = 'admin@dev.local';

-- Verify the API key was created
SELECT id, user_id, name, key_prefix, scopes FROM api_keys WHERE user_id IN (SELECT id FROM users WHERE email = 'admin@dev.local');
